### ISSUE TITLE
📄 [UPLOAD-CRASH] 添加 oh-my-minecraft-client 后崩溃

### ISSUE THREAD

**Issue by 2408248951** [GlobeMC/crashmc.com#152]
### 描述问题

```bash
加了个模组，用于自动切换胸甲和鞘翅
mod名称
oh-my-minecraft-client
```

### 您正在进行的操作是？

```bash
1. 刚加了模组
2. 游戏崩溃
```

### 崩溃日志

```bash
WARNING: Unknown module: cpw.mods.bootstraplauncher specified to --add-exports
jlw: native file exists: 'C:\Users\long\AppData\Roaming\PCL\libjlw-1.3.2.dll'.
jlw: native file checked.
[23:37:05] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[23:37:06] [main/WARN]: Mod resolution failed
[23:37:06] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE ommc-1_20_1 0.5.318+ab0c0cf-beta {depends magiclib-1_20_1 @ [>=0.7.387]}, ROOT_FORCELOAD_SINGLE ommc-1_20_1 0.5.318+ab0c0cf-beta]
[23:37:06] [main/INFO]: Reason: [HARD_DEP ommc-1_20_1 0.5.318+ab0c0cf-beta {depends magiclib-1_20_1 @ [>=0.7.387]}, HARD_DEP magiclib-1_14_4 0.7.364+85d9866-stable {depends minecraft @ [1.14.x]}, HARD_DEP magiclib-1_15_2 0.7.364+85d9866-stable {depends minecraft @ [1.15.x]}, HARD_DEP magiclib-1_16_5 0.7.364+85d9866-stable {depends minecraft @ [1.16.x]}, HARD_DEP magiclib-1_17_1 0.7.364+85d9866-stable {depends minecraft @ [1.17.x]}, HARD_DEP magiclib-1_18_2 0.7.364+85d9866-stable {depends minecraft @ [1.18.x]}, HARD_DEP magiclib-1_19_2 0.7.364+85d9866-stable {depends minecraft @ [1.19.2]}, HARD_DEP magiclib-1_19_3 0.7.364+85d9866-stable {depends minecraft @ [1.19.3]}, HARD_DEP magiclib-1_19_4 0.7.364+85d9866-stable {depends minecraft @ [1.19.4]}, HARD_DEP masa_gadget_mod-1_14_4 3.2.318+67ab5b4-stable {depends minecraft @ [1.14.x]}, HARD_DEP masa_gadget_mod-1_15_2 3.2.318+67ab5b4-stable {depends minecraft @ [1.15.x]}, HARD_DEP masa_gadget_mod-1_16_5 3.2.318+67ab5b4-stable {depends minecraft @ [1.16.x]}, HARD_DEP masa_gadget_mod-1_17_1 3.2.318+67ab5b4-stable {depends minecraft @ [1.17.x]}, HARD_DEP masa_gadget_mod-1_18_2 3.2.318+67ab5b4-stable {depends minecraft @ [1.18.x]}, HARD_DEP masa_gadget_mod-1_19_2 3.2.318+67ab5b4-stable {depends minecraft @ [>1.18.2 <=1.19.2]}, HARD_DEP masa_gadget_mod-1_19_3 3.2.318+67ab5b4-stable {depends minecraft @ [1.19.3]}, HARD_DEP masa_gadget_mod-1_19_4 3.2.318+67ab5b4-stable {depends minecraft @ [1.19.4]}]
[23:37:06] [main/INFO]: Fix: add [], remove [], replace [[magiclib-1_20_1 0.7.364+85d9866-stable] -> add:magiclib-1_20_1 0.7.387 ([[0.7.387,∞)])]
[23:37:06] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MagicLib for 1.20.1' (magiclib-1_20_1) 0.7.364+85d9866-stable with version 0.7.387 or later.
Unmet dependency listing:
	 - Mod 'Oh My Minecraft Client for 1.20.1' (ommc-1_20_1) 0.5.318+ab0c0cf-beta requires version 0.7.387 or later of mod 'MagicLib for 1.20.1' (magiclib-1_20_1), but only the wrong version is present: 0.7.364+85d9866-stable!
	 - Mod 'MagicLib for 1.14.4' (magiclib-1_14_4) 0.7.364+85d9866-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.15.2' (magiclib-1_15_2) 0.7.364+85d9866-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.16.5' (magiclib-1_16_5) 0.7.364+85d9866-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.17.1' (magiclib-1_17_1) 0.7.364+85d9866-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.18.2' (magiclib-1_18_2) 0.7.364+85d9866-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.2' (magiclib-1_19_2) 0.7.364+85d9866-stable requires version 1.19.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.3' (magiclib-1_19_3) 0.7.364+85d9866-stable requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'MagicLib for 1.19.4' (magiclib-1_19_4) 0.7.364+85d9866-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.14.4' (masa_gadget_mod-1_14_4) 3.2.318+67ab5b4-stable requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.15.2' (masa_gadget_mod-1_15_2) 3.2.318+67ab5b4-stable requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.16.5' (masa_gadget_mod-1_16_5) 3.2.318+67ab5b4-stable requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.17.1' (masa_gadget_mod-1_17_1) 3.2.318+67ab5b4-stable requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.18.2' (masa_gadget_mod-1_18_2) 3.2.318+67ab5b4-stable requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.19.2' (masa_gadget_mod-1_19_2) 3.2.318+67ab5b4-stable requires any version between 1.18.2 (exclusive) and 1.19.2 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.19.3' (masa_gadget_mod-1_19_3) 3.2.318+67ab5b4-stable requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	 - Mod 'Masa Gadget for 1.19.4' (masa_gadget_mod-1_19_4) 3.2.318+67ab5b4-stable requires version 1.19.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by hejiehao** [comment]
解决方案：更新MagicLib
