### ISSUE TITLE
安卓的一个问题

### ISSUE THREAD

**Issue by xiaojiao248** [GlobeMC/crashmc.com#153]
### 描述问题

```bash
我是安卓的，加光影这样，别人不会
```

### 您正在进行的操作是？

```bash
1. 进入游戏
2. 使用高清修复添加光影
3. 进入游戏
4. 游戏崩溃
```

### 崩溃日志

```bash
Build version: 1.0.7 
Current date: 2023-09-24 21:38:58 
Device: OPPO PHJ110 
OS version: Android 13 (SDK 33) 
 
Stack trace:  
java.lang.RuntimeException: Unable to resume activity {com.tungsten.fcl/com.tungsten.fcl.activity.JVMActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tungsten.fcl.control.MenuCallback.onResume()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5063)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5106)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8374)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tungsten.fcl.control.MenuCallback.onResume()' on a null object reference
	at com.tungsten.fcl.activity.JVMActivity.onResume(JVMActivity.java:127)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1550)
	at android.app.Activity.performResume(Activity.java:8565)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5045)
	... 13 more
```

### 操作系统

Linux

### 客户端 / 服务端

客户端

**Comment by xiaojiao248** [comment]
安卓加不了光影

**Comment by hejiehao** [comment]
你应该要发游戏崩溃日志而不是启动器日志

**Comment by bingxin666** [comment]
针对 Android 系统运行 Java 版 Minecraft 时的崩溃由于各方面原因（处理器架构，渲染器等）暂时不做处理
