### ISSUE TITLE
📄[UPLOAD-CRASH] 神奇的崩溃，直接没游戏窗口，检测不出

### ISSUE THREAD

**Issue by OVCstudio** [GlobeMC/crashmc.com#154]
### 描述问题

```bash
神奇的崩溃，直接没游戏窗口，检测不出
版本：1.19.2 Fabric有Api没optifine
本来用fabric就是为了方便处理崩溃
装了fabric api JAVA为启动器自动选择
```

### 您正在进行的操作是？

```bash
1. 装了81个Fabric MOD（不算优化MOD）
2. 有个优化MOD钠附属Iris不兼容，禁用
3. 再次启动
4. 游戏崩溃
```

### 崩溃日志

```bash
[08:17:32] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.22
[08:17:32] [ForkJoinPool-1-worker-3/WARN]: Mod mcwfurnitures uses the version 3.2.0b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[08:17:32] [ForkJoinPool-1-worker-3/WARN]: Mod create_enchantment_industry uses the version 1.0.1.b which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[08:17:32] [ForkJoinPool-1-worker-11/WARN]: The mod "createsdelight" contains invalid entries in its mod json:
- Unsupported root entry "authors_todo" at line 1 column 364
[08:17:32] [main/WARN]: Warnings were found!
 - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.6.4+mc1.19.2-build.93 recommends version 0.4.2 or later of sodium-extra, which is missing!
	 - You should install version 0.4.2 or later of sodium-extra for the optimal experience.
[08:17:32] [main/INFO]: Loading 204 mods:
	- architectury 6.5.85
	- bclib 2.1.7
	- bebooks 1.4.1
	- bettercombat 1.7.1+1.19
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterfortresses 1.19.2-Fabric-1.0.6
	- betterfurnacesreforged 1.0.2
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betternether 7.1.4
	- betteroceanmonuments 1.19.2-Fabric-2.1.1
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- bettervillage 3.1.0
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- byg 2.0.1.4
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- cfarmersint 0.0.2
	- cloth-config 8.3.103
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- cobblemon 1.3.1+1.19.2
	- corgilib 1.0.0.34
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- create 0.5.1-c-build.1160+mc1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-6
	   |-- forge_tags 3.0
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib_accessors 2.1.1096+1.19.2
	   |-- porting_lib_base 2.1.1096+1.19.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    |-- porting_lib_constants 2.1.1096+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.1096+1.19.2
	   |    |-- porting_lib_loot 2.1.1096+1.19.2
	   |    |-- porting_lib_model_generators 2.1.1096+1.19.2
	   |    |-- porting_lib_model_loader 2.1.1096+1.19.2
	   |    \-- porting_lib_models 2.1.1096+1.19.2
	   |-- porting_lib_entity 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- porting_lib_extensions 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- porting_lib_fake_players 2.1.1096+1.19.2
	   |-- porting_lib_networking 2.1.1096+1.19.2
	   |-- porting_lib_obj_loader 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    |-- porting_lib_constants 2.1.1096+1.19.2
	   |    \-- porting_lib_model_loader 2.1.1096+1.19.2
	   |-- porting_lib_transfer 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.58-MC1.19.2
	- create_enchantment_industry 1.0.1.b
	   \-- create_dragon_lib 1.0.1
	- createendertransmission 2.0.4-1.19.2-fabric
	- createoreexcavation 1.2.1
	   \-- chunk-storage-api-fabric 1.0.2
	- createsdelight 0.1.0-pre10
	- creeperoverhaul 2.0.9
	- decorative_blocks 3.0.0
	- ecologics 2.1.11
	- enchlevel-langpatch 2.1.2
	- ends_delight 1.19.2-1.0
	- expandeddelight 0.2.5
	- extraalchemy 1.9.0
	- extraorigins 1.19-2
	- fabric-api 0.76.1+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.14.22
	- factory_api 1.19.2-0.1.8
	   \-- team_reborn_energy 2.3.0
	- farmersdelight 1.19.2-1.3.10.1
	- forgeconfigapiport 4.2.11
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- immersive_portals 2.3.2
	   |-- imm_ptl_core 2.3.1
	   \-- q_misc_util 2.3.1
	- itemalchemy 0.7.2
	- java 17
	- libraryferret 4.0.0
	- macawsbridgesbyg 1.19.2-1.3
	- magistuarmory 8.1
	- mcda 2.4.4
	- mcdw 5.0.13-1.19
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	   |-- enchant_giver 1.3.0
	   \-- reach-entity-attributes 2.3.0
	- mcpitanlibarch 1.7.8-1.19.2-fabric
	   \-- org_yaml_snakeyaml 2.0
	- mcwbridges 2.1.0
	- mcwdoors 1.1.0
	- mcwfences 1.0.7
	- mcwfurnitures 3.2.0b
	- mcwlights 1.0.6
	- mcwpaintings 1.0.4
	- mcwtrpdoors 1.1.1
	- mcwwindows 2.2.0
	- minecraft 1.19.2
	- moborigins 1.10.0
	- moonlight 1.19.2-2.2.45
	- morevillagers 4.0.2
	- mtr 1.19.2-3.2.2-hotfix-1
	- naturescompass 1.19.2-2.1.0-fabric
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- origins 1.7.1
	   |-- apoli 2.6.1
	   |    |-- additionalentityattributes 1.0.0+1.19
	   |    |-- calio 1.7.0
	   |    \-- playerabilitylib 1.6.0
	   \-- reach-entity-attributes 2.3.0
	- origins-classes 1.4.0
	- pehkui 3.7.8+1.14.4-1.20.1
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- pfm 1.1.1
	- player-animator 1.0.2
	- railways 1.5.1+fabric-mc1.19.2
	   \-- mm 2.3
	- reeses-sodium-options 1.6.4+mc1.19.2-build.93
	- resourcefulconfig 1.0.20
	- shouldersurfing 2.5
	- smarterfarmers 1.19.2-1.7.1
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- supplementaries 1.19.2-2.3.24
	- tcwm 1.0.0-unofficial-7-SNAPSHOT-2
	- terrablender 2.0.1.166
	- terralith 2.3.11
	- travelersbackpack 1.19.2-8.2.28
	   \-- reach-entity-attributes 2.3.0
	- twilightforest 4.2.357
	   |-- here-be-no-dragons 1.0.0
	   |-- javax_annotation_javax_annotation-api 1.3.2
	   |-- mm 2.3
	   |-- porting_lib 2.1.727+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   \-- reach-entity-attributes 2.3.0
	- villager_enchanter 0.1
	- with_thursday 1.0.1
	- yungsapi 1.19.2-Fabric-3.8.9
	   \-- org_javassist_javassist 3.28.0-GA
	- z_mcwroofsbyg 1.19.2-1.2
[08:17:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/      /ʷʫ ĵ  ³ 6.3  1.20.1fa  /OVCMC9/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:17:33] [main/INFO]: Compatibility level set to JAVA_17
[08:17:33] [main/WARN]: Reference map 'BetterFurnaces-fabric-refmap.json' for betterfurnaces.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:33] [main/WARN]: Reference map 'BetterFurnaces-common-refmap.json' for betterfurnaces-common.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:34] [main/WARN]: Reference map 'FactoryAPI-fabric-refmap.json' for factoryapi.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:34] [main/WARN]: Reference map 'morevillagers-fabric-fabric-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:34] [main/WARN]: Reference map 'NethersDelight-refmap.json' for nethersdelight.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:34] [main/WARN]: Reference map 'smarterfarmers-fabric-refmap.json' for smarterfarmers.mixins.json could not be read. If this is a development environment you can ignore this message
[08:17:34] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/deployer/DeployerTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/deployer/DeployerTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity was not found createsdelight.mixins.json:AccessDeployerTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/AllTileEntities (java.lang.ClassNotFoundException: com/simibubi/create/AllTileEntities)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.AllTileEntities was not found createsdelight.mixins.json:MixinAllTileEntities from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/processing/BasinRecipe (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/processing/BasinRecipe)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.processing.BasinRecipe was not found createsdelight.mixins.json:MixinBasinRecipe from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/processing/BasinTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/processing/BasinTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.processing.BasinTileEntity was not found createsdelight.mixins.json:MixinBasinTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/relays/belt/BeltHelper (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/relays/belt/BeltHelper)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.relays.belt.BeltHelper was not found createsdelight.mixins.json:MixinBeltHelper from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/crusher/CrushingWheelControllerTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/crusher/CrushingWheelControllerTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.crusher.CrushingWheelControllerTileEntity was not found createsdelight.mixins.json:MixinCrushingWheelControllerTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/deployer/DeployerTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/deployer/DeployerTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity was not found createsdelight.mixins.json:MixinDeployerTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/foundation/tileEntity/behaviour/belt/DirectBeltInputBehaviour (java.lang.ClassNotFoundException: com/simibubi/create/foundation/tileEntity/behaviour/belt/DirectBeltInputBehaviour)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.foundation.tileEntity.behaviour.belt.DirectBeltInputBehaviour was not found createsdelight.mixins.json:MixinDirectBeltInputBehaviour from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/fluids/actors/GenericItemFilling (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/fluids/actors/GenericItemFilling)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.fluids.actors.GenericItemFilling was not found createsdelight.mixins.json:MixinGenericItemFilling from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/millstone/MillingRecipe (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/millstone/MillingRecipe)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.millstone.MillingRecipe was not found createsdelight.mixins.json:MixinMillingRecipe from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/millstone/MillstoneTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/millstone/MillstoneTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.millstone.MillstoneTileEntity was not found createsdelight.mixins.json:MixinMillstoneTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/ordana/immersive_weathering/blocks/rustable/RustableBarsBlock (java.lang.ClassNotFoundException: com/ordana/immersive_weathering/blocks/rustable/RustableBarsBlock)
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/itemAssembly/SequencedAssemblyRecipe (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/itemAssembly/SequencedAssemblyRecipe)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.itemAssembly.SequencedAssemblyRecipe was not found createsdelight.mixins.json:MixinSequencedAssemblyRecipe from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/fluids/actors/SpoutTileEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/fluids/actors/SpoutTileEntity)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.fluids.actors.SpoutTileEntity was not found createsdelight.mixins.json:MixinSpoutTileEntity from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/foundation/tileEntity/TileEntityBehaviour (java.lang.ClassNotFoundException: com/simibubi/create/foundation/tileEntity/TileEntityBehaviour)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.foundation.tileEntity.TileEntityBehaviour was not found createsdelight.mixins.json:MixinTileEntityBehaviour from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/AllTileEntities (java.lang.ClassNotFoundException: com/simibubi/create/AllTileEntities)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.AllTileEntities was not found createsdelight.mixins.json:ClientMixinAllTileEntities from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/processing/BasinRenderer (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/processing/BasinRenderer)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.processing.BasinRenderer was not found createsdelight.mixins.json:MixinBasinRenderer from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/millstone/MillstoneRenderer (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/millstone/MillstoneRenderer)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.components.millstone.MillstoneRenderer was not found createsdelight.mixins.json:MixinMillstoneRenderer from mod createsdelight
[08:17:34] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/fluids/actors/SpoutRenderer (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/fluids/actors/SpoutRenderer)
[08:17:34] [main/WARN]: @Mixin target com.simibubi.create.content.contraptions.fluids.actors.SpoutRenderer was not found createsdelight.mixins.json:MixinSpoutRenderer from mod createsdelight
[08:17:39] [main/INFO]: [bclib] Added Config bclib.generator to auto sync (file hash)
[08:17:39] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[08:17:39] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[08:17:39] [main/INFO]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[08:17:39] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/wrench/IWrenchable (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/wrench/IWrenchable)
[08:17:39] [main/WARN]: Error loading class: org/spongepowered/asm/synthetic/args/Args$7 (java.lang.ClassNotFoundException: org/spongepowered/asm/synthetic/args/Args$7)
[08:17:40] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/wrench/IWrenchable
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/wrench/IWrenchable
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[1.19.2-AdventurelandMod-By-OVC.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.2-AdventurelandMod-By-OVC.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.wrench.IWrenchable
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_5871.method_33968(class_5871.java:20) ~[client-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_5871.<clinit>(class_5871.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2939.<clinit>(class_2939.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_5463.<clinit>(class_5463.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30572(class_5458.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[client-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:161) ~[1.19.2-AdventurelandMod-By-OVC.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.2-AdventurelandMod-By-OVC.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	... 8 more
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
发一下crash-report谢谢

**Comment by zyxkad** [comment]
目前看起来像 <https://github.com/Creators-of-Create/Create/issues/3645#issuecomment-1214477517>

**Comment by bingxin666** [comment]
```
[08:17:32] [main/WARN]: Warnings were found! - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.6.4+mc1.19.2-build.93 recommends version 0.4.2 or later of sodium-extra, which is missing! 	 - You should install version 0.4.2 or later of sodium-extra for the optimal experience.
```
可以尝试安装 sodium-extra-mod 后再试一次
或许有帮助？

**Comment by hejiehao** [comment]
遇事不决 Create 和附属版本不匹配
