### ISSUE TITLE
📄[UPLOAD-CRASH] 关于 SoundManager 的 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by duoduoyifan** [GlobeMC/crashmc.com#164]
### 描述问题

```bash
打开游戏就崩溃了，有的时候则是玩着玩着就崩溃了
```

### 您正在进行的操作是？

```bash
1. 打开游戏
2. 游戏崩溃
```

### 崩溃日志

```bash
[spoiler]游戏核心：科技
启动内存：8192 MB
操作系统：Microsoft Windows 11 专业版 x64
————————————————————
CPU：#0Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz 
内存：16317
显卡：#0Radeon (TM) RX 470 Graphics 
————————————————————
核心路径：G:\bakaxl\.minecraft\versions\科技
Java信息：C:\Users\Administrator\AppData\Roaming\.minecraft\cache\java\jre-x64\bin\javaw.exe (Java8.0.51.16 64 Bit)
BakaXL路径：G:\bakaxl\BakaXL_Public_Ver_3.2.3.2.exe
————————————————————
错误日志：
---- Minecraft 崩溃报告 ----
WARNING: coremods are present:
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
Contact their authors BEFORE contacting forge
// You're mean.
Time: 10/3/23 12:30 PM
崩溃类型： Unexpected error
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:233)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1858)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:233)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['duoduo'/338, l='MpServer', x=225.46, y=63.00, z=3356.73]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,252), Chunk: (at 4,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2493269 game time, 2487325 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 58 total; [EntityBabySkeleton['幼年骷髅'/388, l='MpServer', x=265.06, y=24.00, z=3417.49], EntityChicken['鸡'/389, l='MpServer', x=287.72, y=64.00, z=3393.89], EntityCreeper['爬行者'/390, l='MpServer', x=175.50, y=34.00, z=3379.19], EntitySkeleton['骷髅'/392, l='MpServer', x=172.70, y=64.00, z=3383.50], EntityCreeper['爬行者'/393, l='MpServer', x=181.50, y=15.00, z=3371.50], EntityCreeper['爬行者'/394, l='MpServer', x=181.50, y=15.00, z=3367.50], EntitySkeleton['骷髅'/395, l='MpServer', x=181.27, y=15.00, z=3363.51], EntityBat['蝙蝠'/396, l='MpServer', x=179.50, y=16.58, z=3365.61], EntitySkeleton['骷髅'/411, l='MpServer', x=278.50, y=24.00, z=3413.73], EntityBat['蝙蝠'/412, l='MpServer', x=273.27, y=24.53, z=3420.44], EntityBat['蝙蝠'/413, l='MpServer', x=279.39, y=28.10, z=3418.25], EntityBat['蝙蝠'/414, l='MpServer', x=284.50, y=25.10, z=3419.50], EntityZombie['僵尸'/422, l='MpServer', x=178.50, y=15.00, z=3376.50], EntityBat['蝙蝠'/423, l='MpServer', x=179.54, y=22.64, z=3382.61], EntitySkeleton['骷髅'/424, l='MpServer', x=182.50, y=28.00, z=3388.50], EntityCreeper['爬行者'/425, l='MpServer', x=176.50, y=34.00, z=3378.50], EntityCreeper['爬行者'/426, l='MpServer', x=177.50, y=34.00, z=3386.50], EntityItem['item.item.bone'/428, l='MpServer', x=164.81, y=62.00, z=3399.88], EntitySquid['鱿鱼'/433, l='MpServer', x=173.50, y=62.99, z=3323.36], EntitySpider['蜘蛛'/435, l='MpServer', x=235.50, y=67.00, z=3415.50], EntityZombie['僵尸'/436, l='MpServer', x=231.50, y=67.00, z=3414.50], EntityCreeper['爬行者'/437, l='MpServer', x=184.19, y=11.00, z=3331.54], EntityCreeper['爬行者'/438, l='MpServer', x=175.47, y=34.00, z=3350.28], EntityZombie['僵尸'/439, l='MpServer', x=175.49, y=34.00, z=3349.63], EntityCreeper['爬行者'/440, l='MpServer', x=167.60, y=57.00, z=3350.56], EntityCreeper['爬行者'/441, l='MpServer', x=167.52, y=57.00, z=3351.67], EntityCreeper['爬行者'/442, l='MpServer', x=165.74, y=57.00, z=3348.18], EntityCreeper['爬行者'/443, l='MpServer', x=166.50, y=56.00, z=3346.50], EntityCreeper['爬行者'/445, l='MpServer', x=249.50, y=44.00, z=3420.50], EntitySkeleton['骷髅'/448, l='MpServer', x=268.57, y=40.00, z=3331.30], EntitySkeleton['骷髅'/449, l='MpServer', x=262.74, y=38.00, z=3330.36], EntityBat['蝙蝠'/450, l='MpServer', x=267.16, y=40.10, z=3330.25], EntityBat['蝙蝠'/451, l='MpServer', x=262.25, y=38.00, z=3329.25], EntityCow['牛'/452, l='MpServer', x=172.45, y=70.00, z=3300.41], EntitySpider['蜘蛛'/457, l='MpServer', x=199.70, y=68.00, z=3418.70], EntitySkeleton['骷髅'/458, l='MpServer', x=221.50, y=40.00, z=3405.50], EntityZombie['僵尸'/459, l='MpServer', x=211.70, y=66.00, z=3393.70], EntitySkeleton['骷髅'/460, l='MpServer', x=222.50, y=67.00, z=3393.50], EntityPlayerSP['duoduo'/338, l='MpServer', x=225.46, y=63.00, z=3356.73], EntityZombie['僵尸'/340, l='MpServer', x=253.50, y=32.00, z=3327.50], EntitySkeleton['骷髅'/346, l='MpServer', x=164.26, y=68.00, z=3414.63], EntitySquid['鱿鱼'/475, l='MpServer', x=166.48, y=59.20, z=3312.17], EntityItem['item.item.rottenFlesh'/347, l='MpServer', x=165.26, y=68.00, z=3415.84], EntitySquid['鱿鱼'/476, l='MpServer', x=169.46, y=60.57, z=3311.94], EntityCreeper['爬行者'/477, l='MpServer', x=220.50, y=40.00, z=3409.50], EntityItem['item.item.rottenFlesh'/478, l='MpServer', x=222.76, y=68.00, z=3418.03], EntityBat['蝙蝠'/354, l='MpServer', x=231.25, y=59.10, z=3357.25], EntityZombie['僵尸'/355, l='MpServer', x=182.50, y=15.00, z=3397.50], EntityZombie['僵尸'/356, l='MpServer', x=183.50, y=16.00, z=3393.50], EntityCreeper['爬行者'/357, l='MpServer', x=177.56, y=34.00, z=3392.31], EntityCreeper['爬行者'/358, l='MpServer', x=177.94, y=37.00, z=3392.70], EntityCreeper['爬行者'/371, l='MpServer', x=179.50, y=67.00, z=3418.50], EntitySkeleton['骷髅'/372, l='MpServer', x=180.50, y=67.00, z=3417.50], EntitySpider['蜘蛛'/373, l='MpServer', x=188.50, y=69.00, z=3420.50], EntitySheep['羊'/377, l='MpServer', x=209.77, y=63.00, z=3384.50], EntityBat['蝙蝠'/378, l='MpServer', x=179.84, y=14.04, z=3366.39], EntityZombie['僵尸'/379, l='MpServer', x=175.48, y=34.00, z=3369.85], EntitySkeleton['骷髅'/380, l='MpServer', x=170.51, y=55.00, z=3363.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1238946400 bytes (1181 MB) / 3518746624 bytes (3355 MB) up to 8537636864 bytes (8142 MB)
	JVM Flags: 2 total; -Xincgc -Xmx8192M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	| State  | ID                  | Version              | Source                                             | Signature                                |
	|:------ |:------------------- |:-------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2               | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                 | 9.42                 | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                 | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | smoothfontcore      | mc1.12.2-2.1.4       | minecraft.jar                                      | None                                     |
	| LCHIJA | smoothfont          | mc1.12.2-2.1.4       | SmoothFont-mc1.12.2-2.1.4.jar                      | None                                     |
	| LCHIJA | jei                 | 4.16.1.1003          | jei_1.12.2-4.16.1.1003.jar                         | None                                     |
	| LCHIJA | appleskin           | 1.0.14               | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LCHIJA | appliedenergistics2 | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | baubles             | 1.5.2                | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | botania             | r1.10-364            | Botania+r1.10-364.4.jar                            | None                                     |
	| LCHIJA | chameleon           | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal - 副本.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux        | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | cofhcore            | 4.6.6                | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld           | 1.4.0                | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | gunpowderlib        | 1.12.2-1.1           | GunpowderLib-1.12.2-1.1.jar                        | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | waila               | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | dimensionaledibles  | 1.3.2                | DimensionalEdibles-1.12.2-1.3.2.jar                | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | mantle              | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.13.0.183    | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHIJA | extrabotany         | 60                   | ExtraBotany-r1.1-60-beta-hotfix.jar                | None                                     |
	| LCHIJA | extrautils2         | 1.0                  | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | fastleafdecay       | v14                  | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | fpsreducer          | mc1.12.2-1.20        | FpsReducer-mc1.12.2-1.20.jar                       | None                                     |
	| LCHIJA | ic2                 | 2.8.222-ex112        | industrialcraft-2-2.8.222-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorytweaks     | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | ironfurnaces        | 1.3.5                | ironfurnaces-1.3.5.jar                             | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | lanserverproperties | 1.0                  | lanserverproperties-1.0.jar                        | None                                     |
	| LCHIJA | mcjtylib_ng         | 3.5.4                | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| LCHIJA | mekanism            | 1.12.2-9.8.3.390     | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | mekanismgenerators  | 1.12.2-9.8.3.390     | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mousetweaks         | 2.10.1               | MouseTweaks-2.10.1-mc1.12.2.jar                    | None                                     |
	| LCHIJA | nuclearcraft        | 2.18zzz              | NuclearCraft-2.18zzz-1.12.2.jar                    | None                                     |
	| LCHIJA | projecte            | 1.12.2-PE1.4.1       | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCHIJA | reborncore          | 3.19.5               | RebornCore-1.12.2-3.19.5-universal.jar             | None                                     |
	| LCHIJA | rftools             | 7.73                 | rftools-1.12-7.73.jar                              | None                                     |
	| LCHIJA | saltmod             | 1.12.6.2             | SaltyMod-1.12.2-1.12.6.2.jar                       | None                                     |
	| LCHIJA | storagedrawers      | 5.5.0                | StorageDrawers-1.12.2-5.5.0.jar                    | None                                     |
	| LCHIJA | techreborn          | 2.27.3.1084          | TechReborn-1.12.2-2.27.3.1084-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | thermalfoundation   | 2.6.7                | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | thermaldynamics     | 2.5.6                | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCHIJA | veinminer           | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2               | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCHIJA | wailaharvestability | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar              | None                                     |
	| LCHIJA | wawla               | 2.6.275              | Wawla-1.12.2-2.6.275.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | techreborn_compat   | 1.0.0                | TechReborn-ModCompatibility-1.12.2-1.4.0.76.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
  bre.smoothfont.asm.Transformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 22.20.27.09.230330' Renderer: 'Radeon (TM) RX 470 Graphics'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 1
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 科技
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 470 Graphics GL version 4.6.0 Compatibility Profile Context 22.20.27.09.230330, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Minecraft-Mod-Language-Modpack.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 22.20.27.09.230330
	OpenGlRenderer: Radeon (TM) RX 470 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

[/spoiler]
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
这个是某个mod的代码问题，请将所有mod更新到其最新版本。
如果该mod不提供更新，只能删除该mod
