### ISSUE TITLE
📄[UPLOAD-CRASH] Forge 版本过高导致 OptiFine 爆炸

### ISSUE THREAD

**Issue by Seayay** [GlobeMC/crashmc.com#168]
### 描述问题

```bash
爆炸了，这很难理解吗
```

### 您正在进行的操作是？

```bash
1. 启动游戏 
2. 游戏崩溃
```

### 崩溃日志

```bash
[spoiler]游戏核心：1.20.1-forge-47.2.1
启动内存：4096 MB
操作系统：Microsoft Windows 11 家庭中文版 x64
————————————————————
CPU：#013th Gen Intel(R) Core(TM) i7-13620H 
内存：16087
显卡：#0Intel(R) UHD Graphics #1NVIDIA GeForce RTX 4060 Laptop GPU 
————————————————————
核心路径：D:\MC\.minecraft\versions\1.20.1-forge-47.2.1
Java信息：C:\Users\叶某\AppData\Roaming\.minecraft\cache\java\java-runtime-beta\windows-x64\java-runtime-beta\bin\javaw.exe (Java17.0.1.0 64 Bit)
BakaXL路径：D:\MC\BakaXL.exe
————————————————————
错误日志：
由 BakaXL 记录的 Minecraft 日志流: 
2023-10-22 19:40:33,097 main WARN Advanced terminal features are not available in this environment
[19:40:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeclient, --fml.forgeVersion, 47.2.1, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, -Djna.tmpdir=D:\MC\.minecraft\$natives, -Dorg.lwjgl.system.SharedLibraryExtractPath=D:\MC\.minecraft\$natives, -Dio.netty.native.workdir=D:\MC\.minecraft\$natives, -Dminecraft.launcher.brand=BakaXL, -Dminecraft.launcher.version=3.3, cpw.mods.bootstraplauncher.BootstrapLauncher, --username, ziran, --version, 1.20.1-forge-47.2.1, --gameDir, D:\MC\.minecraft\versions\1.20.1-forge-47.2.1, --assetsDir, D:\MC\.minecraft\assets, --assetIndex, 5, --uuid, c94545639d023a51a5f7211e1b3bfc2c, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, BakaXL, --width, 854, --height, 480]
[19:40:33] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.1 by Microsoft; OS Windows 11 arch amd64 version 10.0
[19:40:33] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[19:40:33] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[19:40:34] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[19:40:34] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[19:40:34] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/D:/MC/.minecraft/versions/1.20.1-forge-47.2.1/mods/OptiFine_1.20.1_HD_U_I5_pre4.jar%23158!/
[19:40:34] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: D:\MC\.minecraft\versions\1.20.1-forge-47.2.1\mods\OptiFine_1.20.1_HD_U_I5_pre4.jar
[19:40:34] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[19:40:34] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/MC/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[19:40:34] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Intel(R) UHD Graphics GL version 4.6.0 - Build 31.0.101.4575, Intel
[19:40:34] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [D:\MC\.minecraft\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-srg.jar, D:\MC\.minecraft\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-extra.jar, D:\MC\.minecraft\libraries\net\minecraftforge\forge\1.20.1-47.2.1\forge-1.20.1-47.2.1-client.jar]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:82)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.buildFile(ModJarMetadata.java:41)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.1/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [D:\MC\.minecraft\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-srg.jar, D:\MC\.minecraft\libraries\net\minecraft\client\1.20.1-20230612.114412\client-1.20.1-20230612.114412-extra.jar, D:\MC\.minecraft\libraries\net\minecraftforge\forge\1.20.1-47.2.1\forge-1.20.1-47.2.1-client.jar]
	... 25 more

[/spoiler]
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by hejiehao** [comment]
重装 Forge

**Comment by Seayay** [comment]
> 重装 Forge

把 Forge 降级之后就跑起来了
