### ISSUE TITLE
📄[UPLOAD-CRASH] Inventory connector of simple storage network crashed 

### ISSUE THREAD

**Issue by Squawkykaka** [GlobeMC/crashmc.com#172]
### 描述问题

```bash
Simple storage network crashes the server when a inventory connecter gets placed next to a chest
```

### 您正在进行的操作是？

```bash
1. I restarted the server and removed to storage network controller
2. 
3. 
4. 游戏崩溃
```

### 崩溃日志

```bash
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-12-10 02:45:10
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "com.lothrazar.storagenetwork.api.DimPos.offset(net.minecraft.core.Direction)" because the return value of "com.lothrazar.storagenetwork.api.IConnectable.getPos()" is null
	at com.lothrazar.storagenetwork.capability.CapabilityConnectableLink.addToStackProviderBatch(CapabilityConnectableLink.java:292) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.NetworkModule.executeRequestBatch(NetworkModule.java:312) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.executeRequestBatch(TileMain.java:75) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.updateExports(TileMain.java:253) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.tick(TileMain.java:272) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.serverTick(TileMain.java:259) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:common.level.LevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:littletiles.mixins.json:server.level.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Simple Storage Network (storagenetwork), Version: 1.10.0
		Issue tracker URL: https://github.com/Lothrazar/Storage-Network/issues
		at TRANSFORMER/storagenetwork@1.10.0/com.lothrazar.storagenetwork.capability.CapabilityConnectableLink.addToStackProviderBatch(CapabilityConnectableLink.java:292)
Stacktrace:
	at com.lothrazar.storagenetwork.capability.CapabilityConnectableLink.addToStackProviderBatch(CapabilityConnectableLink.java:292) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.NetworkModule.executeRequestBatch(NetworkModule.java:312) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.executeRequestBatch(TileMain.java:75) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.updateExports(TileMain.java:253) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.tick(TileMain.java:272) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at com.lothrazar.storagenetwork.block.main.TileMain.serverTick(TileMain.java:259) ~[SimpleStorageNetwork-1.20.1-1.10.0.jar%23203!/:1.20.1-1.10.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:common.level.LevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:littletiles.mixins.json:server.level.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: storagenetwork:master // com.lothrazar.storagenetwork.block.main.TileMain
	Block: Block{storagenetwork:master}
	Block location: World: (293,124,-463), Section: (at 5,12,1 in 18,7,-29; chunk contains blocks 288,-64,-464 to 303,319,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{storagenetwork:master}
	Block location: World: (293,124,-463), Section: (at 5,12,1 in 18,7,-29; chunk contains blocks 288,-64,-464 to 303,319,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:common.level.LevelAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:littletiles.mixins.json:server.level.ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Squawkykaka'/66490, l='ServerLevel[world]', x=293.25, y=128.00, z=-460.28]]
	Chunk stats: 4040
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,113,0), Section: (at 0,1,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3426473 game time, 3821534 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 87616 (now: false), thunder time: 35504 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version 5.15.0-1048-oracle
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2196676584 bytes (2094 MiB) / 5465178112 bytes (5212 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 2
	Processor Vendor: aarch64
	Processor Name: 
	Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5970.08
	Virtual memory used (MB): 7759.98
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128M -Xmx8096M
	Server Running: true
	Player Count: 1 / 20; [ServerPlayer['Squawkykaka'/66490, l='ServerLevel[world]', x=293.25, y=128.00, z=-460.28]]
	Data Packs: vanilla, mod:terrablender (incompatible), mod:supermartijn642configlib (incompatible), mod:biomesoplenty (incompatible), mod:rechiseled (incompatible), mod:creativecore, mod:supermartijn642corelib, mod:kotlinforforge (incompatible), mod:flywheel, mod:create, mod:waystones, mod:create_structures, mod:mixinextras (incompatible), mod:create_dragon_lib (incompatible), mod:railways (incompatible), mod:balm, mod:createtrackmap (incompatible), mod:memoryleakfix (incompatible), mod:interiors (incompatible), mod:cloth_config (incompatible), mod:forge, mod:create_enchantment_industry (incompatible), mod:littletiles, mod:ftbessentials (incompatible), mod:ftbultimine (incompatible), mod:architectury (incompatible), mod:ftblibrary (incompatible), mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:polylib, mod:ftbbackups2 (incompatible), mod:inventorysorter (incompatible), mod:playeranimator (incompatible), mod:sophisticatedcore (incompatible), mod:sophisticatedbackpacks (incompatible), mod:emotecraft (incompatible), mod:voicechat (incompatible), mod:sound_physics_remastered (incompatible), mod:titanium (incompatible), mod:easy_villagers, mod:framedblocks, mod:constructionwand, mod:lootr, mod:functionalstorage, mod:framework, mod:jei, mod:curios (incompatible), mod:simplemagnets, mod:storagenetwork, mod:flib, mod:structureessentials (incompatible), mod:journeymap (incompatible), mod:comforts (incompatible), mod:naturescompass, mod:potionsmaster (incompatible), mod:dungeoncrawl, mod:dungeons_arise, mod:chipped (incompatible), mod:structurecompass, mod:spectrelib (incompatible), mod:mr_dungeons_andtaverns (incompatible), mod:resourcefullib (incompatible), mod:cupboard (incompatible), mod:adorn (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.17.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.8.0
		lowcodefml@null
	Mod List: 
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |DONE      |Manifest: NOSIGNATURE
		ftb-essentials-forge-2001.2.2.jar                 |FTB Essentials                |ftbessentials                 |2001.2.2            |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		rechiseled-1.1.5c-forge-mc1.20.jar                |Rechiseled                    |rechiseled                    |1.1.5c              |DONE      |Manifest: NOSIGNATURE
		simplemagnets-1.1.10-forge-mc1.20.jar             |Simple Magnets                |simplemagnets                 |1.1.10              |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.108.504.jar          |Sophisticated Core            |sophisticatedcore             |0.5.108.504         |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |DONE      |Manifest: NOSIGNATURE
		structureessentials-1.20.1-3.2.jar                |Structure Essentials mod      |structureessentials           |1.20.1-3.2          |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.3.4+1.20.1.jar                   |Comforts                      |comforts                      |6.3.4+1.20.1        |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.20.1-1.10.0.jar            |Simple Storage Network        |storagenetwork                |1.10.0              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		mixinextras-forge-0.2.0-rc.4.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.4          |DONE      |Manifest: NOSIGNATURE
		potionsmaster-1.20.1-47.1.70-0.6.0.jar            |PotionsMaster                 |potionsmaster                 |0.6.0               |DONE      |Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.19.1.962.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.19.1.962          |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.3.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.3.3               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |DONE      |Manifest: NOSIGNATURE
		memoryleakfix-forge-1.17+-1.1.2.jar               |Memory Leak Fix               |memoryleakfix                 |1.1.2               |DONE      |Manifest: NOSIGNATURE
		interiors-0.5.2+mc1.20.1-FORGE.jar                |Create: Interiors             |interiors                     |0.5.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-12.0.109-forge.jar                   |Cloth Config v12 API          |cloth_config                  |12.0.109            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.17-universal.jar                |Forge                         |forge                         |47.2.17             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.50    |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.20.1-2.1.57-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.57-1.20.1       |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.20.1-3.0.1.jar                    |Chipped                       |chipped                       |3.0.1               |DONE      |Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.20.1-2.4.29.jar                 |Simple Voice Chat             |voicechat                     |1.20.1-2.4.29       |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.3.0.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.5.3+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.5.3+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.23.jar                        |Titanium                      |titanium                      |3.8.23              |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |DONE      |Manifest: NOSIGNATURE
		StructureCompass-1.20.1-2.0.6.jar                 |Structure Compass Mod         |structurecompass              |2.0.6               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.11_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.11             |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.14+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.14+1.20.1      |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		kffmod-4.8.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.8.0               |DONE      |Manifest: NOSIGNATURE
		easy_villagers-1.20.1-1.0.16.jar                  |Easy Villagers                |easy_villagers                |1.20.1-1.0.16       |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.5+1.20.1.jar                     |Curios API                    |curios                        |5.4.5+1.20.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		create-structures-0.1.1-1.20.1-FORGE.jar          |Create: Structures            |create_structures             |0.1.1               |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-9.1.6.jar                            |FramedBlocks                  |framedblocks                  |9.1.6               |DONE      |Manifest: NOSIGNATURE
		dungeons-and-taverns-3.0.3 [Forge].jar            |Dungeons and Taverns          |mr_dungeons_andtaverns        |3.0.3               |DONE      |Manifest: NOSIGNATURE
		ftb-ultimine-forge-2001.1.2.jar                   |FTB Ultimine                  |ftbultimine                   |2001.1.2            |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.19.jar            |Resourceful Lib               |resourcefullib                |2.1.19              |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.20.1-2.11.jar                  |Construction Wand             |constructionwand              |1.20.1-2.11         |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-2001.1.4.jar                    |FTB Library                   |ftblibrary                    |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-2001.1.4.jar                      |FTB Teams                     |ftbteams                      |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-2001.2.4.jar                     |FTB Chunks                    |ftbchunks                     |2001.2.4            |DONE      |Manifest: NOSIGNATURE
		lootr-1.20-0.7.30.73.jar                          |Lootr                         |lootr                         |0.7.29.68           |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.1.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.1          |DONE      |Manifest: NOSIGNATURE
		functionalstorage-1.20.1-1.2.6.jar                |Functional Storage            |functionalstorage             |1.20.1-1.2.6        |DONE      |Manifest: NOSIGNATURE
		Adorn-5.0.0+1.20.1-forge.jar                      |Adorn                         |adorn                         |5.0.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		flib-1.20.1-0.0.11.jar                            |flib                          |flib                          |0.0.11              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		create-track-map-1.4+mc1.20.1-neoforge.jar        |Create Track Map              |createtrackmap                |1.4                 |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		polylib-forge-2000.0.3-build.97.jar               |PolyLib                       |polylib                       |2000.0.3-build.97   |DONE      |Manifest: NOSIGNATURE
		ftbbackups2-forge-1.20-1.0.23.jar                 |FTB Backups 2                 |ftbbackups2                   |1.0.23              |DONE      |Manifest: NOSIGNATURE
		create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.7.g             |DONE      |Manifest: NOSIGNATURE
		LittleTiles_ALPHA_v1.6.0-pre070_mc1.20.1.jar      |LittleTiles                   |littletiles                   |1.6.0-pre070        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a1986074-eb5e-4788-9e12-42e912036b0b
	FML: 47.2
	Forge: net.minecraftforge:47.2.17
```

### 操作系统

Linux

### 客户端 / 服务端

服务端

**Comment by zkitefly** [comment]
https://github.com/Lothrazar/Storage-Network/issues/509
