### ISSUE TITLE
1.20.4-Fabric 0.15.6-OptiFine_I7_pre2 PCL2 启动崩溃

### ISSUE THREAD

**Issue by Harry-Wayne** [GlobeMC/crashmc.com#195]
### 描述问题

```bash
1.20.4-Fabric 0.15.6-OptiFine_I7_pre2 PCL2 启动崩溃
```

### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 崩溃日志

```bash
[16:35:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.6
[16:35:02] [main/WARN]: Warnings were found!
 - Mod 'BetterF3' (betterf3) 9.0.0 recommends version 8.0.0 or later of modmenu, which is missing!
	 - You should install version 8.0.0 or later of modmenu for the optimal experience.
[16:35:02] [main/INFO]: Loading 105 mods:
	- ambientsounds 5.3.5
	- appleskin 2.5.1+mc1.20.3
	- architectury 11.0.11
	- attributefix 24.0.1
	- badpackets 0.6.0
	- betterf3 9.0.0
	- bookshelf 23.0.2
	- carpet 1.4.128+v231205
	- chat_heads 0.10.30
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- collective 7.30
	- controlling 15.0.2
	- creativecore 2.11.16
	   \-- net_neoforged_bus 7.2.0
	- doubledoors 5.2
	- enchdesc 20.0.1
	- entityculling 1.6.3.1
	- fabric-api 0.95.1+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.47+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.15+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.10+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.0.0+25e1b4764f
	   |-- fabric-data-generation-api-v1 13.1.22+78d798af4f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.0+44c0f8c64f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.72+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.21+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.30+78d798af4f
	   |-- fabric-loot-api-v2 2.1.5+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.60+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.9+06274a474f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.18+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.52+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.33+78d798af4f
	   |-- fabric-rendering-v0 1.1.55+df3654b34f
	   |-- fabric-rendering-v1 3.1.0+0d29db764f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.16+78d798af4f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.8+e84342304f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- ferritecore 6.0.3
	- firstperson 2.3.0
	- fpsreducer 1.20.4-2.7
	- inventoryprofilesnext 1.10.9
	- java 17
	- jei 17.0.0.37
	- journeymap 5.9.20
	   \-- journeymap-api-fabric 1.20.2-1.9-fabric-SNAPSHOT
	- kirin 1.17.0+1.20.4
	- libipn 4.0.1
	- minecraft 1.20.4
	- mousetweaks 2.25
	- nochatreports 1.20.4-v2.5.0
	- optifabric 1.14.3
	   |-- mm 2.3
	   \-- optifabric-libs 1.14.3
	- presencefootsteps 1.11.1
	- roughlyenoughitems 14.0.688
	   \-- error_notifier 1.0.9
	- roughlyenoughprofessions 2.2.0
	- searchables 1.0.3
	- wthit 10.1.0
[16:35:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/PCL2/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:35:03] [main/INFO]: Compatibility level set to JAVA_17
[16:35:03] [main/INFO]: OptiFine was NOT detected.
[16:35:03] [main/INFO]: OptiFabric was detected.
[16:35:03] [main/INFO]: bre2el.fpsreducer.mixin.MinecraftClientMixin will be applied.
[16:35:03] [main/INFO]: bre2el.fpsreducer.mixin.KeyboardMixin will be applied.
[16:35:03] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[16:35:03] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will be applied.
[16:35:05] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[16:35:06] [main/ERROR]: Mixin apply for mod optifabric failed optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric -> net.minecraft.class_761: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric]
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:360) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class carpet/mixins/LevelRenderer_pausedShakeMixin targetting net.minecraft.class_761
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:94) ~[optifabric-1.14.3.jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:59) ~[optifabric-1.14.3.jar:?]
	at me.modmuss50.optifabric.compat.carpet.CarpetExtraMixinPlugin.preApply(CarpetExtraMixinPlugin.java:43) ~[optifabric-1.14.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1358) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1259) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 23 more
[16:35:06] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric] from phase [DEFAULT] in config [optifabric.compat.carpet.extra-new-mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.carpet.extra-new-mixins.json:LevelRendererExtraMixin from mod optifabric]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:360) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class carpet/mixins/LevelRenderer_pausedShakeMixin targetting net.minecraft.class_761
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:94) ~[optifabric-1.14.3.jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:59) ~[optifabric-1.14.3.jar:?]
	at me.modmuss50.optifabric.compat.carpet.CarpetExtraMixinPlugin.preApply(CarpetExtraMixinPlugin.java:43) ~[optifabric-1.14.3.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1358) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1259) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:315) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:286) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:178) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[1.20.4-Fabric%200.15.6-OptiFine_I7_pre2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 8 more
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by Rovniced** [comment]
optifabric 的问题 好像没装 optifine？ 

> [16:35:03] [main/INFO]: OptiFine was NOT detected.
> [16:35:03] [main/INFO]: OptiFabric was detected.

**Comment by Pigeon0v0** [comment]
OptiFabric 删了
