### ISSUE TITLE
[服务端] 高版本fabric端模组:server-Hats引发崩溃

### ISSUE THREAD

**Issue by AresConnor** [GlobeMC/crashmc.com#196]
### 描述问题

```bash
引用该模组issue:https://github.com/WerDei/Server-Hats/issues/11
将物品装到实体头上可能会出现崩溃.

截止目前该模组issue未被解决(issue opening),并且reddit上的一些老哥和我都遇到了同样的问题。
```

### 您正在进行的操作是？

```bash
1. 服务端安装server-Hats后启动。
2. 将物品装到实体上例如村民、假人等
3. 游戏崩溃
```

### 崩溃日志

```bash
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-01-27 13:53:32
Description: Exception ticking world

java.lang.IncompatibleClassChangeError: Found class net.minecraft.class_2342, but interface was expected
	at net.minecraft.class_2315.dispenseHat(class_2315.java:4545)
	at net.minecraft.class_2315$Anonymous$4e9f33edd8ef425d88423cb9c5038491.method_10135(DispenserBlockMixin.java:35)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at net.minecraft.class_2315.method_10012(class_2315.java:105)
	at net.minecraft.class_2315.method_9588(class_2315.java:128)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1203)
	at net.minecraft.class_3218.method_14189(class_3218.java:750)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:330)
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$292(MinecraftServer.java)
	at net.minecraft.server.MinecraftServer.wrapOperation$cbm000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:6431)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2315.dispenseHat(class_2315.java:4545)
	at net.minecraft.class_2315$Anonymous$4e9f33edd8ef425d88423cb9c5038491.method_10135(DispenserBlockMixin.java:35)
	at net.minecraft.class_2347.dispense(class_2347.java:15)
	at net.minecraft.class_2315.method_10012(class_2315.java:105)
	at net.minecraft.class_2315.method_9588(class_2315.java:128)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:1203)
	at net.minecraft.class_3218.method_14189(class_3218.java:750)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:330)
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$292(MinecraftServer.java)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Ares_Connor'/77, l='ServerLevel[world]', x=185.94, y=128.00, z=-155.14]]
	Chunk stats: 2209
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-32,64,-64), Section: (at 0,0,0 in -2,4,-4; chunk contains blocks -32,0,-64 to -17,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 23089338 game time, 16701462 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 31596 (now: false), thunder time: 25402 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 119
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1681)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:951)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 21.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3363666920 bytes (3207 MiB) / 4294967296 bytes (4096 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-14900K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Microsoft Hyper-V 视频
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=10.0.20348.1
	Graphics card #1 name: Microsoft Remote Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.20348.1
	Memory slot #0 capacity (MB): 3968.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4224.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: Other
	Virtual memory max (MB): 10588.92
	Virtual memory used (MB): 6627.97
	Swap memory total (MB): 2397.37
	Swap memory used (MB): 330.82
	JVM Flags: 2 total; -Xmx6G -Xms4G
	Fabric Mods: 
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.40
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.40
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.40
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.40
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.40
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.40
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.40
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.40
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.40
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.40
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.40
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.40
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.40
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.40
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.40
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.40
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.40
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.40
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.40
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.40
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.128+v231205
		carpet-extra: Carpet Extra 1.4.118
		carpet-tis-addition: Carpet TIS Addition 1.55.0
			conditional-mixin: conditional mixin 0.4.1
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.30
		essential_commands: Essential Commands 0.35.0-mc1.20.4
			ec-core: Essential Commands Core 1.3.0-mc1.20.4
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 2.0
			placeholder-api: Placeholder API 2.3.0+1.20.3
			playerabilitylib: Pal 1.9.0
		fabric-api: Fabric API 0.93.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.46+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.83+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.19+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.4+b7e146354f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.17+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.15+78d798af4f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.52+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.7+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		floodgate: Floodgate-Fabric 2.2.0-SNAPSHOT
			cloud: Cloud 1.8.4
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.4
				cloud_commandframework_cloud-core_: cloud-core 1.8.4
				cloud_commandframework_cloud-services_: cloud-services 1.8.4
				io_leangen_geantyref_geantyref: geantyref 1.3.13
		gca: GugleCarpetAddition 2.7.0-1.20.4
		geyser-fabric: Geyser-Fabric 2.2.0-SNAPSHOT
		healingcampfire: Healing Campfire 5.3
		invview: InvView 1.4.14-1.20.4+
			sgui: sgui 1.3.0+1.20.2
		java: Java HotSpot(TM) 64-Bit Server VM 21
		jline4mcdsrv: JLine for Minecraft Dedicated Server 0.4.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			org_fusesource_jansi_jansi: jansi 2.4.0
			org_jline_jline: jline 3.23.0
			org_jline_jline-terminal-jansi: jline-terminal-jansi 3.23.0
		magiclib: MagicLib 0.7.398+fe2125a-stable
			magiclib-1_20_4: MagicLib for 1.20.4 0.7.398+fe2125a-stable
		minecraft: Minecraft 1.20.4
		pca-1_20_4: Plusls Carpet Addition 0.3.190+9e97daa-beta
		server-hats: Server Hats 0.15
		servux: Servux 0.1.0
		spark: spark 1.10.58
		syncmatica: Syncmatica 1.20.2-0.3.11
		textile_backup: Textile Backup 3.1.3-1.20
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.22
			org_tukaani_xz: xz 1.9
	Server Running: true
	Player Count: 2 / 50; [class_3222['sakura_identive'/76, l='ServerLevel[world]', x=1825.47, y=77.00, z=-955.85], class_3222['Ares_Connor'/77, l='ServerLevel[world]', x=185.94, y=128.00, z=-155.14]]
	Data Packs: vanilla, fabric, file/enderman_unholdable (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by zyxkad** [comment]
```
		syncmatica: Syncmatica 1.20.2-0.3.11
```
看起来像是把低版本的mod装到高版本了

**Comment by Pigeon0v0** [comment]
长时间无 Reply 先关了，有问题再打开

**Comment by AresConnor** [comment]
> ```
> 		syncmatica: Syncmatica 1.20.2-0.3.11
> ```
> 
> 看起来像是把低版本的mod装到高版本了

抱歉，之前因为一些事情没能关注。这个服务端所使用的Syncmatica是支持的1.20.4的，文件名有一定的迷惑性。在我删掉这个版本的server-hat模组之后，服务端运行了几周后，没有新的崩溃。

**Comment by AresConnor** [comment]
可以查看上文中所给出的mod相关issue，崩溃症状相同，至今仍未关闭，有理由怀疑该问题并没有修复（事情有点多，就不试以后得版本了）。

**Comment by AresConnor** [comment]
相关模组issue指路 WerDei/Server-Hats#11
