### ISSUE TITLE
📄[UPLOAD-CRASH] 请输入标题

### ISSUE THREAD

**Issue by XXJNOTFOUND** [GlobeMC/crashmc.com#204]
### 描述问题

```bash
直接死掉..
```

### 您正在进行的操作是？

```bash
li开服崩溃
刚打开脚本就这样
```

### 崩溃日志

```bash
[iXiangPro@VM-20-8-centos 1.20.4]$ bash mc.sh
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-240) Host                                                                                                             : Linux 4.18.0-536.el8.x86_64 (amd64)
Loading libraries, please wait...
2024-02-02 14:34:41,219 ServerMain ERROR Cannot access RandomAccessFile java.io.                                                                                                             FileNotFoundException: logs/latest.log (Permission denied) java.io.FileNotFoundE                                                                                                             xception: logs/latest.log (Permission denied)
        at java.base/java.io.RandomAccessFile.open0(Native Method)
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:213)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFil                                                                                                             eManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccess                                                                                                             FileManager.java:232)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFil                                                                                                             eManager$RollingRandomAccessFileManagerFactory.createManager(RollingRandomAccess                                                                                                             FileManager.java:204)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(Abs                                                                                                             tractManager.java:144)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager                                                                                                             (OutputStreamManager.java:100)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFil                                                                                                             eManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:1                                                                                                             07)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppende                                                                                                             r$Builder.build(RollingRandomAccessFileAppender.java:132)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppende                                                                                                             r$Builder.build(RollingRandomAccessFileAppender.java:53)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build                                                                                                             (PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPlug                                                                                                             inObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigur                                                                                                             e(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize                                                                                                             (AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(Abst                                                                                                             ractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerCo                                                                                                             ntext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:                                                                                                             253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(Abstrac                                                                                                             tLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFac                                                                                                             tory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(Abstract                                                                                                             LoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFact                                                                                                             ory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:426)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:73)
        at org.bukkit.craftbukkit.Main.main(Main.java:326)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:842)

2024-02-02 14:34:41,222 ServerMain ERROR Could not create plugin of type class o                                                                                                             rg.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for elemen                                                                                                             t RollingRandomAccessFile: java.lang.IllegalStateException: ManagerFactory [org.                                                                                                             apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$Rollin                                                                                                             gRandomAccessFileManagerFactory@2359b9db] unable to create manager for [logs/lat                                                                                                             est.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingRandom                                                                                                             AccessFileManager$FactoryData@3bd883a2] java.lang.IllegalStateException: Manager                                                                                                             Factory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileM                                                                                                             anager$RollingRandomAccessFileManagerFactory@2359b9db] unable to create manager                                                                                                              for [logs/latest.log] with data [org.apache.logging.log4j.core.appender.rolling.                                                                                                             RollingRandomAccessFileManager$FactoryData@3bd883a2]
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(Abs                                                                                                             tractManager.java:146)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager                                                                                                             (OutputStreamManager.java:100)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFil                                                                                                             eManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:1                                                                                                             07)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppende                                                                                                             r$Builder.build(RollingRandomAccessFileAppender.java:132)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppende                                                                                                             r$Builder.build(RollingRandomAccessFileAppender.java:53)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build                                                                                                             (PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPlug                                                                                                             inObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigur                                                                                                             e(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize                                                                                                             (AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(Abst                                                                                                             ractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerCo                                                                                                             ntext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:                                                                                                             253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(Abstrac                                                                                                             tLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFac                                                                                                             tory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(Abstract                                                                                                             LoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFact                                                                                                             ory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:426)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:73)
        at org.bukkit.craftbukkit.Main.main(Main.java:326)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:842)

2024-02-02 14:34:41,223 ServerMain ERROR Unable to invoke factory method in clas                                                                                                             s org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for ele                                                                                                             ment RollingRandomAccessFile: java.lang.IllegalStateException: No factory method                                                                                                              found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileA                                                                                                             ppender java.lang.IllegalStateException: No factory method found for class org.a                                                                                                             pache.logging.log4j.core.appender.RollingRandomAccessFileAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findF                                                                                                             actoryMethod(PluginBuilder.java:260)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build                                                                                                             (PluginBuilder.java:136)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPlug                                                                                                             inObject(AbstractConfiguration.java:1138)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1063)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConf                                                                                                             iguration(AbstractConfiguration.java:1055)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigur                                                                                                             e(AbstractConfiguration.java:664)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize                                                                                                             (AbstractConfiguration.java:258)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(Abst                                                                                                             ractConfiguration.java:304)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerCo                                                                                                             ntext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext                                                                                                             .java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:                                                                                                             253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log                                                                                                             4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(Abstrac                                                                                                             tLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFac                                                                                                             tory.java:61)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(Abstract                                                                                                             LoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFact                                                                                                             ory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:426)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
        at com.mojang.logging.LogUtils.getLogger(LogUtils.java:62)
        at net.minecraft.server.Main.<clinit>(Main.java:73)
        at org.bukkit.craftbukkit.Main.main(Main.java:326)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:842)

2024-02-02 14:34:41,233 ServerMain ERROR Null object returned for RollingRandomA                                                                                                             ccessFile in Appenders.
2024-02-02 14:34:41,238 ServerMain ERROR Appender File cannot be located. Refere                                                                                                             nce ignored
[14:34:46 WARN]: Can not write to file server.properties, skipping.
[14:34:46 INFO]: Environment: Environment[sessionHost=https://sessionserver.moja                                                                                                             ng.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:34:46 ERROR]: Failed to start the minecraft server
java.nio.file.AccessDeniedException: ./world/session.lock
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90                                                                                                             ) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)                                                                                                              ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)                                                                                                              ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvid                                                                                                             er.java:181) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:298) ~[?:?]
        at java.nio.channels.FileChannel.open(FileChannel.java:357) ~[?:?]
        at net.minecraft.util.DirectoryLock.create(DirectoryLock.java:23) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAcce                                                                                                             ss.<init>(LevelStorageSource.java:533) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource.validateAndCreat                                                                                                             eAccess(LevelStorageSource.java:439) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:205) ~[paper-1.20.4.jar:git-                                                                                                             Paper-405]
        at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:gi                                                                                                             t-Paper-405]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app                                                                                                             :?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

### 操作系统

Linux

### 客户端 / 服务端

服务端

**Comment by bingxin666** [comment]
似乎缺少对于文件夹的写入权限
请尝试通过root账户或使用docker容器运行Minecraft Server

**Comment by XXJNOTFOUND** [comment]
收到了，确实是这样的，感谢大佬😭
