### ISSUE TITLE
📄[UPLOAD-CRASH] 未知的错误

### ISSUE THREAD

**Issue by xgvalley** [GlobeMC/crashmc.com#207]
### 描述问题

```bash
GlobeMC未收录我的崩溃信息。
```

### 您正在进行的操作是？

```bash
1. 使用HMCL打开Java版Minecraft的1.20.4版本，没有安装forge、fabric等。
2. 进入一个新的世界（无论是本地的地图还是服务器）
3. 游戏崩溃
4. 获取崩溃信息zip文件
5. 使用GlobeMC导入该zip文件
6. 显示的分析结果是：“本工具还未收录您所遇到的错误，请点击下方按钮前往 GitHub 反馈。”
```

### 崩溃日志

```bash
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

-- Uptime --
Details:
	JVM uptime: 71.247s
	Wall uptime: 60.404s
	High-res time: 58.961s
	Client ticks: 912 ticks / 45.600s
Stacktrace:
	at evi.d(SourceFile:2564)
	at evi.c(SourceFile:995)
	at evi.f(SourceFile:911)
	at net.minecraft.client.main.Main.main(SourceFile:265)

-- Affected level --
Details:
	All players: 1 total; [fsj['Xigu'/6, l='ClientLevel', x=2.50, y=-60.00, z=-5.50]]
	Chunk stats: 961, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 11 game time, 11 day time
	Server brand: vanilla
	Server type: Integrated singleplayer server
	Tracked entity count: 1

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Mac OS X (x86_64) version 14.3
	Java Version: 18.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 468199272 bytes (446 MiB) / 1140850688 bytes (1088 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 15360.00
	Virtual memory used (MB): 13591.50
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 6751.06
	JVM Flags: 10 total; -Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods
	Launched Version: 1.20.4
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.2+13
	Backend API: Apple M1 GL version 4.1 Metal - 88, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched; Server jar signature and brand is untouched
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: 
	Current Language: zh_cn
	Locale: zh_CN_#Hans
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [ane['Xigu'/6, l='ServerLevel[WORLD]', x=2.50, y=-60.00, z=-5.50]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
#@!@# Game crashed! Crash report saved to: #@!@# /Users/xuhui/Library/Application Support/minecraft/crash-reports/crash-2024-02-03_09.14.08-client.txt
```

### 操作系统

Mac

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
@xgvalley 请上传完整崩溃日志

**Comment by xgvalley** [comment]
完整崩溃日志：
[minecraft-exported-crash-info-2024-02-03T10-42-20.zip](https://github.com/GlobeMC/crashmc.com/files/14303808/minecraft-exported-crash-info-2024-02-03T10-42-20.zip)

**Comment by zkitefly** [comment]
> 完整崩溃日志： [minecraft-exported-crash-info-2024-02-03T10-42-20.zip](https://github.com/GlobeMC/crashmc.com/files/14303808/minecraft-exported-crash-info-2024-02-03T10-42-20.zip)

该问题是由于当前版本的 `authlib-injector` 不支持 1.20.4 导致的崩溃，因为 HMCL 的自动选择下载源问题导致更新 `authlib-injector` 失败

先把 HMCL 换成这里下载的测试版本  https://gitee.com/Glavo/HMCL-Update#:~:text=.exe%EF%BC%9Ahmcl%2Ddev%2D ，然后在启动器的设置里，按图里的顺序去掉上面的勾，并且把下载源改成「BMCLAPI」，改完之后重启启动器 ![](https://img.kookapp.cn/assets/2023-08/rcKqsL83iv0m907d.png)
