### ISSUE TITLE
📄[UPLOAD-CRASH] 模组导致崩溃

### ISSUE THREAD

**Issue by Structuretxwd** [GlobeMC/crashmc.com#245]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
[11:49:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:49:17] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:49:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:49:17] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[11:49:17] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_60, running on Windows 10:amd64:10.0, installed at D:\MCLDownload\ext\jre-v64-220420\jre8
[11:49:17] [main/INFO] [FML]: Searching D:\Release 2.6.13\.minecraft\versions\Mustard Virus by Forge Labs\mods for mods
[11:49:17] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [Xaero的世界地图] XaerosWorldMap_1.37.8_Forge_1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:49:17] [main/WARN] [FML]: The coremod XaeroWorldMapPlugin (xaero.map.core.XaeroWorldMapPlugin) is not signed!
[11:49:17] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [实体渲染机制优化] entityculling-1.12.2-1.6.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:49:17] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\Release 2.6.13\.minecraft\versions\Mustard Virus by Forge Labs for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 11 more
Caused by: java.lang.ClassNotFoundException: zone.rong.mixinbooter.IEarlyMixinLoader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2855.jar:?]
	... 11 more
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.reflect.InvocationTargetException
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:51)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:49:17] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 6 more
```

### 您正在进行的操作是？

```bash
1. 启动
2. 游戏崩溃
```

### 日志文件

[错误报告-2024-3-17_星期日_11.47.zip](https://github.com/GlobeMC/crashmc.com/files/14626130/-2024-3-17_._11.47.zip)

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
缺少 `zone.rong.mixinbooter`
