### ISSUE TITLE
Opt + Sodium Mod Load Error

### ISSUE THREAD

**Issue by z0z0r4** [GlobeMC/crashmc.com#68]
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.10+build.27 with any version that is compatible with:
		 - optifabric 1.13.25
	 - Replace mod 'Iris' (iris) 1.6.4 with any version that is compatible with:
		 - optifabric 1.13.25
Unmet dependency listing:
	 - Mod 'Iris' (iris) 1.6.4 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	 - Mod 'Sodium' (sodium) 0.4.10+build.27 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.25!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
```

**Comment by bwtx2023** [comment]
作为 Mod 冲突处理

**Comment by hejiehao** [comment]
> 

有，但放在了Mixin
但这却不是Mixin

**Comment by z0z0r4** [comment]
我的评价是缺少常见报错...这个巨常见不过了

**Comment by bwtx2023** [comment]
> 我的评价是缺少常见报错...这个巨常见不过了

就做了三天要啥自行车

待会儿有空加上

**Comment by 2623684696** [comment]
写上了

**Comment by XieXiLin2** [comment]
先交 PR 再关闭。
